# Page settings
baseurl = "corelab.io"
title = "CORE Lab"
languageCode = "en-us"
theme = "hugo-elate-theme"
publishDir = "../co-relab.github.io"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "Richard A Klein"
  description = "CORE Lab Homepage"
  email = "h.ijzerman@gmail.com"
  # Navigation
  [params.navigation]
    brand = "CORE Lab"
    home = "Home"
    work = "Projects"
    testimonials = "Testimonials"
    services = "Opportunities"
    about = "Lab Members" #Order of this one changed in layouts/partials/nav.html 
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10

# Can edit the order of components in layouts/index.html, and menu order in layouts/partials/nav.html  
  
  # Hero section
  [params.hero]
    title = 'Co-Regulation (CORE) Lab.'
    subtitle = 'We study co-regulation in romantic relationships while utilizing open science ideals. We collaborate around the world, but are located at the <a href="https://www.univ-grenoble-alpes.fr">Université Grenoble Alpes</a>.'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Papers"
    description = "Check out publications and/or preprints from the lab. We try to ensure all our work is available to the public, so if you can't find a paper let us know!"
    url = "http://papers.ssrn.com/sol3/cf_dev/AbsByAuth.cfm?per_id=1923044" #This just links to Hans' SSRN for now, thinking of better solutions.
    button = "Access Papers"
    icon = "icon-docs"
    img = "papers.png"

  [[params.intro.item]]
    title = "Open Data/Materials"
    description = "To the extent possible we make materials, data, and analysis scripts publicly available on the Open Science Framework. These may be used for re-analysis or for novel hypotheses."
    url = 'https://osf.io/search/?q=tags:("CORE Lab")&page=1' #This links to a search on OSF for projects tagged "CORE Lab". So, if we stick with this, we should add that tag to all our osf projects.
    button = "Find our datasets"
    icon = "icon-folder"
    img = "COS-Logo-small-1.png"

  [[params.intro.item]]
    title = "Popular Science"
    description = "Are you a non-scientist, interested in solid, well-written psychological science? Check out the Open Access In-Mind Magazine (available in English, Dutch, Italian, and German)."
    url = "http://www.in-mind.org/"
    button = "Go to In-Mind"
    icon = "icon-bulb"
    img = "inmind.png"

  [params.intro.video]
    enable = false
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = true
    title = "Projects"
    description = "Here's a sample of the work we do."
    footertext = ''

    [[params.work.row]]
      img = "penguins-429128_1920.jpg"
      alt = "Penguins Image"
      title = "Human Penguin Project"
      subtitle = "International collaboration investigating the link between social environment and core body temperature."
      url = "https://osf.io/2rm5b/" 

# To enable external URLs here, I had to edit layouts/partials/work.html.
# Line 16 from: <a href="images/{{ .img }}" class="fh5co-project-item image-popup to-animate">
# to: <a href="{{ .url }}" class="fh5co-project-item to-animate">

    [[params.work.row]]
      img = "cup-939479_1920.jpg"
      alt = "Cold Glass Image"
      title = "Socially Thermoregulated Thinking"
      subtitle = "Past experiences, and a current manipulation of physical temperature, affect thinking about our loved ones."
      url = "https://psyarxiv.com/25dmj"

    [[params.work.row]]
      img = "stroopml.png"
      alt = "Image3"
      title = "Machine Learning and the Stroop Effect"
      subtitle = "Revisiting what predicts performance on a classic effect using new statistics (conditional random forests)."
      url = "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2805205"

  # Testimonials section
  [params.testimonials]
    enable = false
    title = "Testimonials"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"



  # Services section
  # Note: The description lengths below need to be roughly equal or the formatting will get messed up.
  [params.services]
    enable = true
    title = "Opportunities/Openings"
    description = "We usually have various opportunities to work with/in the lab. Read about those below, and get in touch if you want to learn more. We work in English, but we also invite French (or other) speakers who want to improve their English."

    [[params.services.item]]
      title = "Internships"
      description = "We welcome interns from fields like psychology, computer science, statistics, or others. We currently have several students scheduled for 8-week visits."
      icon = "icon-graduation"

    [[params.services.item]]
      title = '<a href = "">PhD/Masters Grant 1</a>'
      description = "Placeholder for now. Grant will be described here. Just be aware that for some reason the length of this description sometimes messes up the formatting. I think it has more problems with very short descriptions."
      icon = "icon-graduation"
      
    [[params.services.item]]
      title = '<a href = "">Post-Doc Grant 1</a>'
      description = "Placeholder for now. Grant will be described here. Just be aware that for some reason the length of this description sometimes messes up the formatting. I think it has more problems with very short descriptions."
      icon = "icon-graduation"

      [[params.services.item]]
      title = '<a href = "">Post-Doc Grant 2</a>'
      description = "Placeholder for now. Grant will be described here. Just be aware that for some reason the length of this description sometimes messes up the formatting. I think it has more problems with very short descriptions."
      icon = "icon-graduation"

  # About section
  [params.about]
    enable = true
    title = "Lab Members"
#    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.about.item]]
      name = '<a href="http://www.hansijzerman.org/">Hans IJzerman</a>'
      position = 'Principal Investigator'
      description = "PhD in Social Psychology from Utrecht University and Associate Professor at UGA. Directs lab strategy."
      img = "hans_twitter.jpeg"
      alt = "Person1"
      social = [
        ["icon-globe", "http://www.hansijzerman.org/"],
        ["icon-folder", "https://osf.io/3hsfj/"],
        ["icon-google", "https://scholar.google.com/citations?user=KC7FG9QAAAAJ"],        
        ["icon-twitter", "https://twitter.com/hansijzerman"]
      ]

    [[params.about.item]]
      name = '<a href="https://raklein.github.io/">Richard Klein</a>'
      position = "Post-Doc"
      description = "PhD in Social Psychology from the University of Florida. Handles complex datasets and performs statistical analyses."
      img = "klein.cos.photo.jpg"
      alt = "RichardKlein"
      social = [
        ["icon-globe", "https://raklein.github.io/"],
        ["icon-folder", "https://osf.io/tmwry/"],
        ["icon-google", "https://scholar.google.com/citations?user=wxW6e0sAAAAJ"],
        ["icon-github", "https://github.com/raklein"]
      ]

    [[params.about.item]]
      name = 'Lison Neyroud'
      position = "Research Manager"
      description = "MA in Psychology from the Université Grenoble Alpes. Manages participant recruitment and keeps things running in the lab."
      img = "person3.jpg"
      alt = "Person3"
      social = [
      ["icon-folder", "https://osf.io/n75jp/"]
      ]      

  # Counters section
  [params.counters]
    enable = false
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = true
    form = true
    title = "Get in touch"
    description = "Always open to questions/comments/collaborations. If you're interested in a position in the lab, please include: <br><li>The grant/opportunity you're interested in.</li><li>Current academic/professional status.</li><li>A brief comment about open science.</li>"
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Université Grenoble Alpes <br> BP 47 - 38040 GRENOBLE Cedex 9 <br> FRANCE"],
#        ["icon-phone", "(123) 465-6789"],
        ["icon-envelope", "h.ijzerman@gmail.com"],
        ["icon-globe", '<a href="https://corelab.io" target="_blank">Corelab.io</a>']
      ]

    name = "Name"
    email = "Email"
#    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = 'Powered by the <a href="https://github.com/saey55/hugo-elate-theme">Elate Hugo port</a>.'
#    links = [
#        ["icon-twitter", "#twitter"],
#        ["icon-facebook", "#facebook"],
#        ["icon-youtube", "#youtube"]
#      ]
