# Page settings
baseurl = "corelab.io"
title = "CORE Lab"
languageCode = "en-us"
theme = "hugo-elate-theme"
publishDir = "../co-relab.github.io"

# Can add background image in themes/hugo-elate-theme/layouts/partials/hero.html or replace full_image_2.jpg
# Adjust transparency in style.css (search 'opacity:')

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "Richard A Klein"
  description = "CORE Lab Homepage"
  email = "h.ijzerman@gmail.com"
  # Navigation
  [params.navigation]
    brand = "CORE Lab"
    home = "Home"
    work = "Projects"
    testimonials = "Lab Friends" # I commented out this tab in partials/nav.html so it isn't displayed
    services = "Opportunities"
    about = "Lab Members" #Order of this one changed in layouts/partials/nav.html 
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10

# Can edit the order of components in layouts/index.html, and menu order in layouts/partials/nav.html  
  
  # Hero section
  [params.hero]
    title = '<br><br>Co-Regulation (CORE) Lab.'
    subtitle = 'We study co-regulation in romantic relationships. We study social thermoregulation. We rely on open science ideals. We collaborate with researchers around the world, but are located at the <a href="https://www.univ-grenoble-alpes.fr">Université Grenoble Alpes</a>.'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Papers"
    description = "Check out publications and/or preprints from the lab. We try to ensure all our work is available to the public, so if you can't find a paper let us know!"
    url = "http://papers.ssrn.com/sol3/cf_dev/AbsByAuth.cfm?per_id=1923044" #Can we make a separate page where we merge our papers from psyarxiv?
    button = "Access Papers"
    icon = "icon-docs"
    img = "papers.png"

  [[params.intro.item]]
    title = "Open Data/Materials"
    description = "To the extent possible we make materials, data, and analysis scripts publicly available on the Open Science Framework. These may be used for re-analysis or for novel hypotheses."
    url = 'https://osf.io/search/?q=tags:("CORE Lab")&page=1' #This links to a search on OSF for projects tagged "CORE Lab". So, if we stick with this, we should add that tag to all our osf projects.
    button = "Find our datasets"
    icon = "icon-folder"
    img = "COS-Logo-small-1.png"

  [[params.intro.item]]
    title = "Lab Philosophy"
    description = "Doing science is really hard. Here, we document the workflow of the lab and expectations for lab members. Includes templates for OSF projects to make open science easier."
    url = "lab_philosophy.docx" #the file is under /content/
    button = "Download"
    icon = "icon-bulb"
    img = "doors.jpg"

  [params.intro.news] #did some heavy editing of params/intro.html to add this section
    enable = true
    title = "Announcements"
    description = "&bull; Justin Mah (University of Alberta) will be joining the lab as intern in May<br>&bull; Last submitted manuscript that we participated in was for the Psych Science Accelerator: https://psyarxiv.com/785qu/<br>&bull; Armel Soubeiga (Université Grenoble Alpes) will be joining the lab as an intern in May; Nazanin Kafaee (Western Ontario University) will be joining the lab as intern in 2019!<br>&bull"
# Above description is less tidy than the rest because I hacked it in to the intro. Will try to tidy it later.

  [params.intro.video]
    enable = false
    title = "Watch the video."
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = true
    title = "Projects"
    description = "Here's a sample of the work we do."
    footertext = ''

    [[params.work.row]]
      img = "penguins-429128_1920.jpg"
      alt = "Penguins Image"
      title = "Human Penguin Project"
      subtitle = "International collaboration investigating the link between social environment and core body temperature."
      url = "https://osf.io/2rm5b/" 

# To enable external URLs here, I had to edit layouts/partials/work.html.
# Line 16 from: <a href="images/{{ .img }}" class="fh5co-project-item image-popup to-animate">
# to: <a href="{{ .url }}" class="fh5co-project-item to-animate">

    [[params.work.row]]
      img = "cup-939479_1920.jpg"
      alt = "Cold Glass Image"
      title = "Socially Thermoregulated Thinking"
      subtitle = "Past experiences, and a current manipulation of physical temperature, affect thinking about our loved ones."
      url = "https://psyarxiv.com/25dmj"

    [[params.work.row]]
      img = "stroopml.png"
      alt = "Stroop figure"
      title = "Machine Learning and the Stroop Effect"
      subtitle = "Revisiting what predicts performance on a classic effect using new statistics (conditional random forests)."
      url = "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2805205"

    [[params.work.row]]
      img = "ml1.png"
      alt = "Many Labs 1 figure"
      title = "Many Labs 1"
      subtitle = "36 labs replicated 13 classic psychology studies to investigate cultural and contextual predictors of replicability."
      url = "https://osf.io/wx7ck/"
      
    [[params.work.row]]
      img = "transparency.jpg"
      alt = "Transparency Image"
      title = "Transparency Guide"
      subtitle = "One of our researchers participated in a collaboration to write a practical guide for more transparent science."
      url = "https://psyarxiv.com/rtygm"
      
      [[params.work.row]]
      img = "oxford.jpeg"
      alt = "Oxford Image"
      title = "Oxford Bibliography Guide"
      subtitle = "Two of our researchers participated in a collaboration to write an Oxford Bibliography on replication initiatives in psychology."
      url = "https://psyarxiv.com/rtygm"
      
      [[params.work.row]]
      img = "SVO.jpeg"
      alt = "SVO Image"
      title = "Replication Attachment-Social Value Orientation"
      subtitle = "One of our researchers conducted a (failed) replication of a famous finding in the literature (showing a relation between attachment security and Social Value Orientation)."
      url = "https://psyarxiv.com/rtygm"

  # Testimonials section
  # I edited partials/testimonials.html to remove the quotes and change this to a friends-of-lab section.
<<<<<<< HEAD
=======
  # Due to this, we add urls with html code (<a href=""></a>). See Below
  # All images need to be square (e.g. 400 x 400) or the spacing of the page will be messed up
  # Also, seems finicky to the length of text. May need to use abbreviations for names/affiliations.
>>>>>>> 67ab47656113541e443f0b59e5b0864fa77821ea
  [params.testimonials]
    enable = true
    title = "Friends of the lab"

    [[params.testimonials.item]]
      person = '<a href="https://jamescoan.com/">Jim Coan</a><br> University of Virginia'
      img = "jimcoan.jpeg" 
      alt = "jimcoan" # This is just text that gets displayed if the img file fails to load

    [[params.testimonials.item]]
      person = '<a href="https://cals.arizona.edu/fcs/faculty/emily_butler">Emily Butler</a><br> University of Arizona'
      img = "butler.jpeg"
      alt = "butler"

    [[params.testimonials.item]]
      person = '<a href="https://www.su.se/english/profiles/tamm-1.182300">Maria Koptjesvakaja-Tamm</a><br> Stockholm University'
      img = "tamm.jpeg"
      alt = "tamm"

    [[params.testimonials.item]]
      person = '<a href="http://julianneholtlunstad.byu.edu/">Julianne Holt-Lunstad</a><br> Brigham Young University'
      img = "holtlunstad.jpeg"
      alt = "holtlunstad"

    [[params.testimonials.item]]
      person = '<a href="http://www.ru.nl/english/people/hasselman-f/">Fred Hasselman</a><br>Radboud University Nijmegen'
      img = "hasselman.jpg"
      alt = "hasselman"

    [[params.testimonials.item]]
      person = '<a href="http://www.kateratliff.com/">Kate Ratliff</a><br>University of Florida'
      img = "ratliff.jpeg"
      alt = "ratliff"

    [[params.testimonials.item]]
      person = '<a href="https://psysciacc.org/">Psych Science Accelerator</a><br>Worldwide Collaboration'
      img = "psa.png"
      alt = "psa"

    [[params.testimonials.item]]
      person = '<a href="https://psychology.as.virginia.edu/people/profile/cre2am">Charlie Ebersole</a><br>University of Virginia'
      img = "ebersole.jpg"
      alt = "ebersole"

    [[params.testimonials.item]]
      person = '<a href="https://www.tilburguniversity.edu/webwijs/show/j.j.a.denissen.htm">Jaap Denissen</a><br>Tilburg University'
      img = "denissen.jpg"
      alt = "denissen"

    [[params.testimonials.item]]
      person = '<a href="http://lindenberg.academiaworks.com/">Sigi Lindenberg</a><br>Rijksuniversiteit Groningen'
      img = "lindenberg.jpeg"
      alt = "lindenberg"

    [[params.testimonials.item]]
      person = '<a href="https://sites.google.com/site/michelangelovianello/">Michelangelo Vianello</a><br>University of Padova'
      img = "vianello.jpeg"
      alt = "vianello"

    [[params.testimonials.item]]
      person = '<a href="https://www.anthro.ucla.edu/faculty/alan-page-fiske">Alan Fiske</a><br>University of California, LA'
      img = "fiske.jpg"
      alt = "fiske"

    [[params.testimonials.item]]
      person = '<a href="http://www.unipo.sk/pedagogicka-fakulta/katedry/kpepp/ropovik">Ivan Ropovik</a><br>University of Presov'
      img = "ropovik.jpg"
      alt = "ropovik"
      
      [[params.testimonials.item]] 
      person = '<a href="http://www.in-mind.org">In-Mind Foundation</a><br>One of our researchers is the founder of In-Mind'
      img = "inmind.png"
      alt = "inmind"
      
      [[params.testimonials.item]] 
      person = '<a href="https://research.vu.nl/en/persons/paula-sterkenburg">Paula Sterkenburg</a><br>Vrije Universiteit Amsterdam'
      img = "sterkenburg.jpg"
      alt = "sterkenburg"
      
      [[params.testimonials.item]] 
      person = '<a href="http://www.tilapronk.nl/">Tila Pronk</a><br>Tilburg University'
      img = "pronk.jpg"
      alt = "pronk"
      
      [[params.testimonials.item]] 
      person = '<a href="http://www.tilapronk.nl/">Tila Pronk</a><br>Tilburg University'
      img = "pronk.jpg"
      alt = "pronk"
      
      [[params.testimonials.item]] 
      person = '<a href="http://english.telhai.ac.il/content/prof-yizhar-lavner">Yizhar Lavner</a><br>Tel Hai College'
      img = "Lavner.jpg"
      alt = "lavner"
      
      [[params.testimonials.item]] 
      person = '<a href="http://emotionregulationlab.com/?page_id=41">Mattie Tops</a><br>Vrije Universiteit Amsterdam'
      img = "tops.jpeg"
      alt = "tops"
      
    [[params.testimonials.item]] #Layout doesn't like the second line of affiliiations, so Brian has to come last.
      person = '<a href="https://www.projectimplicit.net/nosek/">Brian Nosek</a><br>University of Virginia<br>Center for Open Science'
      img = "nosek.jpeg"
      alt = "nosek"

  # Services section
  # Note: The description lengths below need to be roughly equal or the formatting will get messed up.
  [params.services]
    enable = true
    title = "Opportunities/Openings"
    description = "We sometimes have job openings at the lab. In the meantime, if you are interested in working with us, there are various grants you can receive and where we can support you in writing. We have posted some of these below and will update as we learn about more. We work in English, but we also invite French (or other) speakers who want to improve their English."

    [[params.services.item]]
      title = "Internships"
      description = "We welcome interns from fields like psychology, computer science, statistics, or others. We currently have several students scheduled for 8-week visits."
      icon = "icon-graduation"

    [[params.services.item]]
      title = '<a href = "">Postdoc Grant - Marie Curie</a>'
      description = "The Marie Curie grant is an excellent opportunity for scholars outside of France wanting to come to France. Deadline for this call is September 12, 2018"
      icon = "icon-graduation"
      link = "https://ec.europa.eu/research/mariecurieactions/actions/get-funding_en"
      

  # About section
  [params.about]
    enable = true
    title = "Lab Members"
#    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.about.item]]
      name = '<a href="http://www.hansijzerman.org/">Hans IJzerman</a>'
      position = 'Principal Investigator'
      description = "PhD in Social Psychology from Utrecht University and Associate Professor at UGA. Directs lab strategy."
      img = "hans_twitter.jpeg"
      alt = "Person1"
      social = [
        ["icon-globe", "http://www.hansijzerman.org/"],
        ["icon-folder", "https://osf.io/3hsfj/"],
        ["icon-google", "https://scholar.google.com/citations?user=KC7FG9QAAAAJ"],        
        ["icon-twitter", "https://twitter.com/hansijzerman"]
      ]

    [[params.about.item]]
      name = '<a href="https://raklein.github.io/">Richard Klein</a>'
      position = "Post-Doc"
      description = "PhD in Social Psychology from the University of Florida. Handles complex datasets and performs statistical analyses."
      img = "klein.cos.photo.jpg"
      alt = "RichardKlein"
      social = [
        ["icon-globe", "https://raklein.github.io/"],
        ["icon-folder", "https://osf.io/tmwry/"],
        ["icon-google", "https://scholar.google.com/citations?user=wxW6e0sAAAAJ"],
        ["icon-github", "https://github.com/raklein"]
      ]

    [[params.about.item]]
      name = 'Lison Neyroud'
      position = "Research Manager"
      description = "MA in Psychology from the Université Grenoble Alpes. Manages participant recruitment and keeps things running in the lab."
      img = "person3.jpg"
      alt = "Person3"
      social = [
      ["icon-folder", "https://osf.io/n75jp/"]
      ]      

  # Counters section
  [params.counters]
    enable = false
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = true
    form = true
    title = "Get in touch"
    description = "If you're interested in a position in the lab, contact us! In your contact request, please include why you are interested in working on concepts related to thermoregulation/co-regulation. Please also include: </li><li>Which opportunity (e.g., grant) you're interested in.</li><li>Current academic/professional status.</li><li>A brief statement about your commitment to open science.</li>"
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Université Grenoble Alpes <br> BP 47 - 38040 GRENOBLE Cedex 9 <br> FRANCE"],
#        ["icon-phone", "(123) 465-6789"],
        ["icon-envelope", "h.ijzerman@gmail.com"],
        ["icon-globe", '<a href="https://corelab.io" target="_blank">Corelab.io</a>']
      ]

    name = "Name"
    email = "Email"
#    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = 'Powered by the <a href="https://github.com/saey55/hugo-elate-theme">Elate Hugo port</a>.'
#    links = [
#        ["icon-twitter", "#twitter"],
#        ["icon-facebook", "#facebook"],
#        ["icon-youtube", "#youtube"]
#      ]
